name: Deploy to VPS 

on:
  push:
    branches:
      - main # Jalankan otomatisasi hanya jika ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH to Herza VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}       # IP VPS lo (disembunyikan)
          username: ${{ secrets.VPS_USERNAME }}   # Username root (disembunyikan)
          key: ${{ secrets.VPS_SSH_PASSWORD }}     # SSH Private Key lo (disembunyikan)
          port: 22
          script: |
            
            cd /Documents/Clumbo-website
            
            
            git reset --hard origin/main
            
            
            git pull origin main
            
            
            docker compose up -d --build
